apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eyego
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eyego
  template:
    metadata:
      labels:
        app: eyego
    spec:
      containers:
      - name: eyego
        image: 599164248778.dkr.ecr.us-east-1.amazonaws.com/hello-eyego:latest        
        ports:
        - containerPort: 3000
