apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eyego
  labels:
    app: hello-eyego
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-eyego
  template:
    metadata:
      labels:
        app: hello-eyego
    spec:
      containers:
      - name: hello-eyego
        image: 599164248778.dkr.ecr.me-south-1.amazonaws.com/hello-eyego:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10